// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bibjnfnovfzuefslwlib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpYmpuZm5vdmZ6dWVmc2x3bGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODgzNzksImV4cCI6MjA3MzQ2NDM3OX0.ITTEA5v2InYItVIntTHBuZQjmkA5cDaQwdWuQNB3kYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});